import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Qwitcher_Grypen } from 'next/font/google';
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const qwitcher = Qwitcher_Grypen({
  subsets: ['latin'],
  variable: "--font-qwitcher",
  weight: ['400', '700'], // optional weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
  className={`${poppins.variable} ${qwitcher.variable} font-sans antialiased bg-ivory-background text-forest-green`}
>

        <div className="flex flex-col min-h-screen">
          <Header />
          <main className="flex-grow ">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
