import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Qwitcher_Grypen } from 'next/font/google';
import { Lora } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
});

const qwitcher = Qwitcher_Grypen({
  subsets: ['latin'],
  variable: "--font-qwitcher",
  weight: ['400', '700'], // optional weights
});

const lora = Lora({
  subsets: ["latin"],  // include character sets you need
  weight: ["400", "700"], // normal and bold
  variable: "--font-lora", // optional CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
  className={`${montserrat.variable} ${qwitcher.variable} ${lora.variable} font-sans antialiased  text-forest-green`}
>

        <div className="flex flex-col min-h-screen">
          <Header />
          <main className="flex-grow ">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
